module_irc = "IRC"

############
# IRC Join #
############
mt_irc_join = "Join"
md_irc_join = "Join a IRC Channel."
msg_irc_join_channel = "Trying to join %s"

#############
# autologin #
#############
msg_autologin = "You have been authenticated via WHOIS."
